name: nlp-mt

channels:
  - conda-forge

dependencies:
  - python=3.11
  - jupyterlab
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - tqdm
  - scikit-learn
  - scipy
  - pytorch
  - gensim
  - nltk